### ISSUE TITLE
How to see Node Number as is referenced in Timer Node? 

### ISSUE THREAD

**Issue by ibadmore** [chrisgoringe/cg-quicknodes#13]
Where can one find the number associated with each node in the Timer Node? Thank you!

**Comment by Cornox** [comment]
My nodes also won't show any numbers. I've restarted my anaconda environment + tried chrome and firefox browser but it won't show the node number like in the example images. 
![image](https://github.com/chrisgoringe/cg-quicknodes/assets/111305892/ca8c580e-93af-4ce6-948b-0b805d7e767a)

**Comment by chrisgoringe** [comment]
I think it's one of the options in the comfy manager

**Comment by ibadmore** [comment]
<img width="208" alt="Screenshot 2023-12-25 at 11 06 20 PM" src="https://github.com/chrisgoringe/cg-quicknodes/assets/122062584/8545101e-4817-4cb4-a264-328989eb594e">
ohh gotcha yeah looks like its in the settings under "Badge"

Thanks!
